#
#   ____    _   _                      ____                           _
# / ___|  | | (_)  _ __ ___     ___  |  _ \    ___   _ __     __ _  (_)  _ __
# \___ \  | | | | | '_ ` _ \   / _ \ | |_) |  / _ \ | '_ \   / _` | | | | '__|
#  ___) | | | | | | | | | | | |  __/ |  _ <  |  __/ | |_) | | (_| | | | | |
# |____/  |_| |_| |_| |_| |_|  \___| |_| \_\  \___| | .__/   \__,_| |_| |_|
#                                                   |_|
#
# Created by JustJustin
#

# Settings for rank plugin.
settings:
  use-primary-group: true
  assign-groups-by-permissions: false
  # Priority group-finding-list
  primary-group-finding-list:
    - "Owner"
    - "Admin"
    - "Helper"
    - "default"

# Settings for hand repair.
repair-hand:
  # The cooldown, in seconds.
  cooldown: 10
  # The sound played on repair.
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: "0.5F"
    volume: "1.0F"

# Settings for inventory repair.
repair-all:
  # The cooldown, in seconds.
  cooldown: 100
  # The sound played on repair.
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: "0.5F"
    volume: "1.0F"

error:
  # The sound played.
  sound:
    enabled: true
    sound: "ENTITY_WITHER_DEATH"
    pitch: "0.5F"
    volume: "1.0F"

reload:
  # The sound played.
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: "0.5F"
    volume: "1.0F"

# Permission list
permissions:
  bypass:
    countdown: "slimerepair.bp.countdown"
    cost: "slimerepair.bp.cost"
  repair:
    hand: "slimerepair.repair.hand"
    all: "slimerepair.repair.all"


# Settings for the costs of commands
costs:
  # Settings for costs of the item in the hand
  repair-in-hand:
    # Put costs in order (use default for the main-permission: slimerepair.repair.hand)
    default:
      cost: 10
      aliases: []
  # Settings for costs of the item in all the inventory
  repair-all:
    # Put costs in order (use default for the main-permission: slimerepair.repair.all)
    default:
      cost: 10
      aliases: []